<a href="https://colab.research.google.com/github/AhmedA245/Project-Heart-Failure-prediction/blob/main/Category_column_creations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Import

In [ ]:
project_id = 'heart-failure-project'

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
import pandas as pd

from google.cloud import bigquery

client = bigquery.Client(project='heart-failure-project')

df = client.query('''

SELECT *
  FROM
    `heart-failure-project.HeartFailureData.df_CPK_cat`
  ''').to_dataframe()

In [ ]:
df.describe()

,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time
count,5000.000000,5000.0,5000.0,5000.000000,5000.000000,5000.0,5000.0
mean,60.291800,586.7606,37.7346,265075.404370,1.369106,136.8082,130.6788
std,11.697385,976.733979,11.514855,97999.758622,1.009750,4.464236,77.325928
min,40.000000,23.0,14.0,25100.000000,0.500000,113.0,4.0
25%,50.000000,121.0,30.0,215000.000000,0.900000,134.0,74.0
50%,60.000000,248.0,38.0,263358.030000,1.100000,137.0,113.0
75%,68.000000,582.0,45.0,310000.000000,1.400000,140.0,201.0
max,95.000000,7861.0,80.0,850000.000000,9.400000,148.0,285.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       5000 non-null   float64
 1   anaemia                   5000 non-null   Int64
 2   creatinine_phosphokinase  5000 non-null   Int64
 3   diabetes                  5000 non-null   Int64
 4   ejection_fraction         5000 non-null   Int64
 5   high_blood_pressure       5000 non-null   Int64
 6   platelets                 5000 non-null   float64
 7   serum_creatinine          5000 non-null   float64
 8   serum_sodium              5000 non-null   Int64
 9   sex                       5000 non-null   Int64
 10  smoking                   5000 non-null   Int64
 11  time                      5000 non-null   Int64
 12  DEATH_EVENT               5000 non-null   Int64
 13  age_category              5000 non-null   object
dtypes: Int64(10), float64(3), object(1)
memory usage: 595.8+ KB

# Category Column creation

In [ ]:
df['sex'] = df['sex']

In [ ]:
Female = [0]
Male = [1]

In [ ]:
df['sex'].unique()

<IntegerArray>
[1, 0]
Length: 2, dtype: Int64

In [ ]:
#this code only works for boolean datatype so we didnt use it. we used the code below this one.
for i in df["sex"]:
  if i in Female:
    df["sex"].replace([i], "Female", inplace=True)
  elif i in Male:
    df["sex"].replace([i], "Male", inplace=True)

<ipython-input-23-27b12fec1e50>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["sex"].replace([i], "Male", inplace=True)

TypeError: Invalid value 'Male' for dtype Int64

In [ ]:
#the datatype was int64 not boolean
#we overwritten our original column. which is not cool. remember to create a new column instead next time.
df["sex"] = df["sex"].astype(str).replace({ "1": "Male", "0": "Female" })
df

In [ ]:
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,age_category
0,50.0,0,318,0,30,1,211000.00,2.00,138,Male,0,60,1,middle_aged
1,60.0,0,582,0,30,1,461000.00,2.00,132,Male,0,40,1,senior
2,79.0,1,55,0,30,1,461000.00,2.00,132,Male,0,30,1,senior
3,95.0,1,582,0,30,0,461000.00,2.00,132,Male,0,50,1,elderly
4,95.0,1,112,0,30,0,461000.00,2.00,132,Male,0,50,1,elderly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,0,senior
4996,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,0,senior
4997,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,0,senior
4998,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,0,senior
4999,75.0,0,119,0,45,1,305000.00,1.18,137,Male,1,209,0,senior

In [ ]:

df_sex_cat = df

In [ ]:
from google.cloud import bigquery
import pandas_gbq

project_id = 'heart-failure-project'
dataset_name = 'HeartFailureData'
table_id = 'df_sex_cat'
df_to_bq = df_sex_cat
pandas_gbq.to_gbq(df_to_bq, f'{dataset_name}.{table_id}', project_id=project_id)

100%|██████████| 1/1 [00:00<00:00, 642.12it/s]

In [ ]:
df_death_cat = df

In [ ]:
df["DEATH_EVENT"] = df["DEATH_EVENT"].astype(str).replace({ "1": "deceased", "0": "alive" })
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,age_category
0,50.0,0,318,0,30,1,211000.00,2.00,138,Male,0,60,deceased,middle_aged
1,60.0,0,582,0,30,1,461000.00,2.00,132,Male,0,40,deceased,senior
2,79.0,1,55,0,30,1,461000.00,2.00,132,Male,0,30,deceased,senior
3,95.0,1,582,0,30,0,461000.00,2.00,132,Male,0,50,deceased,elderly
4,95.0,1,112,0,30,0,461000.00,2.00,132,Male,0,50,deceased,elderly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,alive,senior
4996,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,alive,senior
4997,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,alive,senior
4998,75.0,0,582,0,40,0,263358.03,1.18,137,Male,0,107,alive,senior
4999,75.0,0,119,0,45,1,305000.00,1.18,137,Male,1,209,alive,senior

In [ ]:
from google.cloud import bigquery
import pandas_gbq

project_id = 'heart-failure-project'
dataset_name = 'HeartFailureData'
table_id = 'df_death_cat'
df_to_bq = df_death_cat
pandas_gbq.to_gbq(df_to_bq, f'{dataset_name}.{table_id}', project_id=project_id)

NameError: name 'df_death_cat' is not defined

In [ ]:
df_smoker_cat = df

In [ ]:
df["smoking"] = df["smoking"].astype(str).replace({ "1": "smoker", "0": "non-smoker" })

In [ ]:
df["DEATH_EVENT"] = df["DEATH_EVENT"].astype(str).replace({ "1": "deceased", "0": "alive" })

In [ ]:
from google.cloud import bigquery
import pandas_gbq

project_id = 'heart-failure-project'
dataset_name = 'HeartFailureData'
table_id = 'df_DEATH_EVENT_cat'
df_to_bq = df_DEATH_EVENT_cat
pandas_gbq.to_gbq(df_to_bq, f'{dataset_name}.{table_id}', project_id=project_id)

100%|██████████| 1/1 [00:00<00:00, 1143.49it/s]

In [ ]:
df_cat_strings = df

In [ ]:
#Add serum creatinine category
df['Ejection_Fraction_category'] = pd.cut(
    df['ejection_fraction'],
    bins=[14, 39, 49, 80],  # Define the boundaries for low, normal, and high creatinine levels
    labels=['Reduced_EF', 'Mildly_Elevated_EF', 'Preserved_EF'],
    include_lowest=True
)

In [ ]:
from google.cloud import bigquery
import pandas_gbq

project_id = 'heart-failure-project'
dataset_name = 'HeartFailureData'
table_id = 'df_cat_strings'
df_to_bq = df_cat_strings
pandas_gbq.to_gbq(df_to_bq, f'{dataset_name}.{table_id}', project_id=project_id)

100%|██████████| 1/1 [00:00<00:00, 7358.43it/s]

In [ ]:
df.describe()

,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time
count,5000.000000,5000.0,5000.0,5000.000000,5000.000000,5000.0,5000.0
mean,60.291800,586.7606,37.7346,265075.404370,1.369106,136.8082,130.6788
std,11.697385,976.733979,11.514855,97999.758622,1.009750,4.464236,77.325928
min,40.000000,23.0,14.0,25100.000000,0.500000,113.0,4.0
25%,50.000000,121.0,30.0,215000.000000,0.900000,134.0,74.0
50%,60.000000,248.0,38.0,263358.030000,1.100000,137.0,113.0
75%,68.000000,582.0,45.0,310000.000000,1.400000,140.0,201.0
max,95.000000,7861.0,80.0,850000.000000,9.400000,148.0,285.0

In [ ]:
df[df['Ejection_Fraction_category'].isna()]

Empty DataFrame
Columns: [age, anaemia, creatinine_phosphokinase, diabetes, ejection_fraction, high_blood_pressure, platelets, serum_creatinine, serum_sodium, sex, smoking, time, DEATH_EVENT, age_category, serum_sodium_cat, serum_creatinine_cat, CPK_category, Platelets_category, Ejection_Fraction_category]
Index: []

In [ ]:
df.drop(columns= ['ejection_fraction_category', 'Ejection_Fraction_cat', 'Ejection_Fraction_improved'], inplace=True)
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,age_category,serum_sodium_cat,serum_creatinine_cat,CPK_category,Platelets_category,Ejection_Fraction_category
0,60.0,anaemia,180,diabetic,35,non-hypertension,263358.03,1.8,113,Male,smoker,186,alive,senior,low_serum_sodium,high_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Reduced_EF
1,60.0,non-anaemia,1211,diabetic,35,non-hypertension,263358.03,1.8,113,Male,smoker,186,alive,senior,low_serum_sodium,high_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Reduced_EF
2,60.0,non-anaemia,1211,diabetic,35,non-hypertension,263358.03,1.8,113,Male,smoker,186,alive,senior,low_serum_sodium,high_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Reduced_EF
3,60.0,non-anaemia,1211,diabetic,35,non-hypertension,263358.03,1.8,113,Male,smoker,186,alive,senior,low_serum_sodium,high_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Reduced_EF
4,60.0,non-anaemia,1211,diabetic,35,non-hypertension,263358.03,1.8,113,Male,smoker,186,alive,senior,low_serum_sodium,high_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Reduced_EF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,82.0,anaemia,855,diabetic,50,hypertension,321000.00,1.0,145,Female,non-smoker,30,deceased,elderly,normal_serum_sodium,normal_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Preserved_EF
4996,82.0,anaemia,379,diabetic,50,hypertension,321000.00,1.0,145,Female,non-smoker,30,deceased,elderly,normal_serum_sodium,normal_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Preserved_EF
4997,82.0,anaemia,379,diabetic,50,hypertension,321000.00,1.0,145,Female,non-smoker,30,deceased,elderly,normal_serum_sodium,normal_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Preserved_EF
4998,82.0,non-anaemia,1411,diabetic,50,hypertension,321000.00,1.0,145,Female,non-smoker,30,deceased,elderly,normal_serum_sodium,normal_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Preserved_EF
4999,95.0,non-anaemia,582,diabetic,50,hypertension,321000.00,1.0,145,Female,non-smoker,30,deceased,elderly,normal_serum_sodium,normal_serum_creatinine,Highly_Elevated_CPK,Normal_Platelet_Count,Preserved_EF